services:
  - type: web
    name: mern-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env:
      NODE_ENV: production
      PORT: 10000
      MONGODB_URI:
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
    plan: free